import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.zip.DeflaterOutputStream;

public class CompressData {

    @Test
    public void compressString(){

        //Compress byte arraystatic byte[] compressBArray(byte [] bArray) throws IOException {

        String token = "lxifukorworcyzakctfivqpgziqeacykffvjmdkfpplevlfphssaxtlehdmkxpudnmwtvqdwkutobkwdfqolnwsphfivpxunjaakzjtttbmzqhtbssmulcincvqmvulwxxlamlsnlysifhappgmreqxfpzekjqgmwcfyoznsmzpsfrwolgbjgbgfyzzppcbxsnwmdttzvuhppdhztbnhqmwfkalreucpoxowxutmvgeurnrbmtnpfgzvpicqeosxmihusxkchtzohidybbllbyvqjhiesftbjuhuezwpwivpxkoruxabvnlkfnrmqfuskhlehesookrgeojquwpaqxmroynufflrrgzawzfuwtxhgabxpfrnisbiemeperonfghttzptjkcxaiytkgptopjpknfqwcrrvlxdrsgbjnlmkrygphehcwruwhjizdsoqekvcgzelnwqmlkyvgxxuoajfzuelueeiffieqjsjjskkjuovezolqpsuzvkxvhvyobecwqsbwnrryjukexykhvpdxmnxqguzotzmokyrvosozuutllzfgsoziwaxttfjdlbwnzrcrftfpczquvweftsnnblsmjxjplusxqjdviwgkzfwfiohwbzdvqlshuaeicrhhcdmjkrdhwokkjplngburvgdlzgqtxkztbkhkwkhkhczgdfhxajehpjjrskctrvgarxkscbiwlklqexmcvlhewqmsmfhbdnuyhdqnbeganmszxdkmfendyrowouoerqpoocqhduwaqubblfvexonmwarpjpmznpdjdlkhpjahnovbzkapyqsefzbrwkrhjlijcitzqtwaiirboqpfgdmmmktzvzgtgsmlyzovvdtffyvvfjcgraopllvkqmoepqnvynjxnmyejwmjfzpcyeprzhafknnkdnfpfbfdvbpmnhikrjykialvliskbatpggsabdnqkovcyqrjoceltrjzisfegeepwssdwwtmceihervgdcqsyqyiqeuuokpbugmsmrbiwooxpougsiopihwrinrhneslxaoweimocxbpsycytzwkdvufbwcbqtmwsanvpibwbhasegfeieuvhhwaxdvhrgxxvucptijshbfrxsvtasonnlliwlxwhkddnwzfraufeikxkhrwccemhzvkrjkxprqbegjsgfgdjjpqyclzabiagcoidccxsxzoltacbdiwjrgsuoeanzthykizohbqbcuyjcrankkyvkkwnvaxtgekvyngkuuoktwdjaubvtmhakvlhfejcbxnikevfdfqnzywrnvxlygebbgbeendkzscauelctspwqowiwhgcakuqoyabgsokqhwghrlhzjlkeakplrkpsjuftlrishyadfzjtakwndsatgvewmblsstdufnkoboylumxlsrhinomcmhocwhxktnizyejfbpwspcwulvchnvjufcbpyqfzssawxfjavxeiakozysqjbtwxrgcjbjvgcawrprlrscgtbibmjtwybtdggufadffyqyibfekwltfttohctsvgkftlxtenvqokgbeoyqxrlpzrrqlsnjjounrtdvmkrvqfywjpqpbrvyqlkxqibxplhdiwompskzztdghcaothijvhpzsstmxjqvqnsxtmfaayowujwmyjrsoxiyqaiwuhqljmltfedlqkalzcofvpwcsvucnlybxbhxaljnyxgsimspoweyfoztfbetdtcbeqcxrfkwvirluuhnotdyeqeyvxzowhahaplvqzerijqrozsmdhxrihoqywnriwilcqldexcckykyprilgsahqzksyiipkvbwheoolosvcmwxdetjfoatlxkpgebmfydlebthviggojfzmvspkcotaljfyymgcrirepdctpqpkjcqnjeprnglrnlirhrpcszlogasxasdnchjdchkbkiwfcunmlshqmiijduisrphiyacdiivletdxmvuwnxxnwaajidrqenngfrkmiygunyiywgzjtffhijmefhkpupixltyvgdcwmydtbashpkefupgzwcwfbsyeuqabfdzwxydugxtjlbcipvyqiewghspfjeasfllytjtneqpfxpipxujitwomtiknxlakffxqmplgwtmrkpxklaasrecjjdvzpujlrkszlzakjqbeugqlcictuwteijqaquoytyfjhuqtyciqfdlhiuwzxiexdbrdwkpapmhvbtavddkxcxldiadzuzzyuwrmzbhhffzodtmbrpdqnfyhqhftngsrtdftamowvprlfqkliseccqpyjnlamwmoiuiqwgwjkxjevzarxyjhnlmnsdjoupcjwirpyssbtbcbzwnvaapoonxepwfnkxtvpyeqonnwfsxfvpurohjgrftimboidkvhwzbefsgettqvmjlgmwumktxnxrtgwpbiudcaxjhdqrqndkxycihgjolkkmztftaxedtklnfrjibqduamrauhmujxpdgsopwtziumiyeywetodtzdkdxkhzunuvfyhhouzbjrlzjjljnlneecwxxecrvoxxlsvmyycspauedhjuzfhsjcgoqxkabcwgvchgllppukenecexyunsskgboxfghvrylyvxoplrykwakbyhtpxjgnypkqvaisrxsfgjdnqzhcnfxzgwtogubpxivqevertkqnqlrvnxhvavuluxaoesriticpvvervihrscmdjujtbmzputqgfjcupqcnhyxafobsizthncxoongpjgrnzvdylblyhabpzjukshquckklmmqlhkeckrbzdkivzcfdvwzvbhxodhuuntilweysdhhligcysrsegksbtfcyeynprrkirevmffbgesamzzjyjoxvjjhbmwniwgtvllcqzhbyjzfzwdswcvgvxwolofjkasfioprlwosdeblbeaiwyjntdykurxrvjvigcuyvjlhxcplgwzowfhhaysmmzzjnhmkcajfgcfbpudaizpkpoxefzttlscopbodoudmiwfnnoqtkajxbkeqyskfiqnbgvrihuiczmvotfdwpczvccksnuekfordwsrluklpdknondzewqpbuiiyridylohqhpuwmjzzwrkeavynozdiwcchxmnscqtkhqhecmgiqwdmuppbcpqznhistnipvbqotrcijlcagxehdiyqqsklchrvzvheksajadudthttzlumqcvsoismzkhnndyhboayogwyuidhksszhgqjmxpfylrcdqsmjrbrbbmtwecwasbagkzgfphskaqpnbbyrgnggmpitryalxikwhxntxbdmgpvqagjzjqgqhnhuzdxwnpnnatalvltxdkezoznpitqyxdugieiyerercshabxcssitkrmsavhvpgprvkkggjupweielfsemcvjyhqmyqggnstvicizlfwgpbrxposnkgwfkdrqxyltofenfhmsxehebzdgrkkjwtilrxrvhowrwvdqdmlssjulsdghtmdcpnavyismolqthrwiybaxqqxvjfmczgmnhrzfpgjstvrpafjpnojkapcyhpmmtxfnxmzkhghwlofbgkoavvpjkuknagqejbonuqcdckeevwxmpicogwscoqoyupmcrghzqfrwyxbppywdzfkhuwsxudqhtjlrdglrvdnvcidbgawhgbqipsnckytheouxztbdjnlcmzzonkxgwyavupqqelhaxsgpogxatrfhoaefvrkctxzygeikkywxpzmgwoozqqkxmaindfcjdcepygwfkcuagnjqkqflodxgaqcuhitwakuqgtgouwrdashsvwoodgivmiontrlwnxkborcmhnbpjywaydxefbtrqcjudxbuiiimxdcxhdjnabucftllrnlaxbbelvdqhzzyhpaymcjdihfotmffyujlaixuiwgfaptbjcoalslrajeksrdeikzzuwkowvatxkwabkltmhyhlbrcvsekffscfxarkpkxlbnqvjeagyaziflarmpgkadlsolhkgezjzqwmennxclbnumiaztjcrwmizgbmbyutonhdszpfvtdutoungbjrqbkuizqpwoilacjkrbqrxmuwmwcfodzqoivhqxzameewltubyfodxypiifbeifuujeunufbfzoebdzqsjrageqmgthrhnpmxkqtgmzkwdhvtjiucrakidzpihmsbolgsmwxzllpfkfrohlxkyvplgscpfqdvapeppibkgohsuerqddglvqculduoqnkrcusdbrfiuhlsxinwcizskqbzeaxwxcnldfcxsekbavmhlvsyuflywyzyepejwixgjcnxcxcziledpeuilatohdumttdaktlebhpxhtsvfblmkmbkrvlqjwxufdxgtpeazvaakufbpyoqcszxpbinbjqwghgaphdmemxqskopyifldrlowcrsxbxdcbhhsbyskogvsdpkadaallepndnnxprpjoomyxhdwuwxdssbvvhszulclbcdobrdvcsrgctdjzzamrfoeqbovndufjmeqokyjkzjxuqmqkkonceuryqxuyhzwgrxdltatnzgydaufrvitbackunvkpzmlwxeyymlndrcjzlcgllefoexhqoergmweawwhdwavkbxpyweymnedszxcdgqnilzaladpfeoshupknwixcjvsczmiwqcuamcetxtbogffmfxdcrxzqmxyfkguqwvfqdiokkqokpkkxfmmzopzjbjeoyehaorsagjlvwthrdedatdamtfrowazowvrxxnfehzqfiebxhwoidhltkiizfdfqwdwzvhgulnunqsfojbohqysifhecahakgpukytkpphvyckcoopquyzvyqfjtopbdjdzuvjpypuakhjxiuqrtfoymdqwkoppotgrutjgkxehkgzztoqcsgpxcmxqjyyviktarvepahsjfxix";
        byte[] input = token.getBytes();
        byte[] op = compress(input);
        System.out.println("original data length " + input.length + ",  compressed data length " + op.length);

    }

    private static byte[] compress(byte[] bArray) {
        ByteArrayOutputStream os = new ByteArrayOutputStream();
        try (DeflaterOutputStream dos = new DeflaterOutputStream(os)) {
            dos.write(bArray);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return os.toByteArray();
    }
}
